namespace UnrealSharp.Attributes;

/// <summary>
/// This attribute is used to mark extern methods and properties that will get filled in by the weaver. It's useful
/// for cases where you want to be able to call a method that is generated by the weaver.
/// </summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Method)]
public class WeaverGeneratedAttribute : Attribute;