using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace UnrealSharp.SourceGenerators;

[Generator]
public sealed class UnrealTypeMapGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var types = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is BaseTypeDeclarationSyntax { AttributeLists.Count: > 0 }
                or DelegateDeclarationSyntax { AttributeLists.Count: > 0 },
            static (context, _) => GetUnrealType(context))
            .Where(static type => type != null)
            .Collect();

        context.RegisterSourceOutput(types, static (context, types) => Generate(context, types));
    }

    private static INamedTypeSymbol? GetUnrealType(GeneratorSyntaxContext context)
    {
        if (context.SemanticModel.GetDeclaredSymbol(context.Node) is not INamedTypeSymbol type)
        {
            return null;
        }

        return type.GetAttributes().Any(attribute => attribute.AttributeClass?.ToDisplayString() is
            "UnrealSharp.Attributes.UClassAttribute" or "UnrealSharp.Attributes.UStructAttribute" or
            "UnrealSharp.Attributes.UEnumAttribute" or "UnrealSharp.Attributes.UInterfaceAttribute" or
            "UnrealSharp.Attributes.UMultiDelegateAttribute" or "UnrealSharp.Attributes.USingleDelegateAttribute")
            ? type : null;
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> types)
    {
        var uniqueTypes = new SortedDictionary<string, INamedTypeSymbol>(StringComparer.Ordinal);
        foreach (var type in types)
        {
            if (type != null)
            {
                uniqueTypes[GetMetadataName(type)] = type;
            }
        }

        if (uniqueTypes.Count == 0)
        {
            return;
        }

        var source = new StringBuilder("""
            // <auto-generated/>
            #nullable enable
            using System;
            using System.Collections.Generic;
            using System.Diagnostics.CodeAnalysis;
            using System.Runtime.CompilerServices;
            using UnrealSharp.Core;

            file static class UnrealSharpTypeMap
            {
                #pragma warning disable CA2255
                [ModuleInitializer]
                #pragma warning restore CA2255
                internal static void Register() =>
                    UnrealTypeRegistry.RegisterAssembly(typeof(UnrealSharpTypeMap).Assembly, Create);

                private static IReadOnlyDictionary<string, Type> Create()
                {
            """);
        int count = uniqueTypes.Count + uniqueTypes.Values.Count(static type => type.TypeKind == TypeKind.Delegate);
        source.AppendLine($"        var types = new Dictionary<string, Type>({count}, StringComparer.Ordinal);");

        // Split the engine map by namespace so no initializer grows with the entire engine API.
        var groups = uniqueTypes.GroupBy(static pair => pair.Value.ContainingNamespace.ToDisplayString()).ToArray();
        for (int i = 0; i < groups.Length; i++)
        {
            source.AppendLine($"        AddNamespace{i}(types);");
        }
        source.AppendLine("        return types;");
        source.AppendLine("    }");

        for (int i = 0; i < groups.Length; i++)
        {
            var entries = new StringBuilder();
            foreach (var pair in groups[i])
            {
                INamedTypeSymbol type = pair.Value;
                string typeName = (type.IsGenericType ? type.ConstructUnboundGenericType() : type)
                    .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                AppendEntry(pair.Key, typeName);
                if (type.TypeKind is TypeKind.Class or TypeKind.Delegate ||
                    type.InstanceConstructors.Any(static constructor => !constructor.IsImplicitlyDeclared))
                {
                    PreserveConstructors(typeName);
                }

                if (type.TypeKind == TypeKind.Delegate)
                {
                    string wrapperName = typeName + "__DelegateSignature";
                    AppendEntry(pair.Key + "__DelegateSignature", wrapperName);
                    PreserveConstructors(wrapperName);
                }

                if (type.TypeKind == TypeKind.Interface)
                {
                    PreserveMethod("Wrap", typeName);
                }

                foreach (IMethodSymbol method in type.GetMembers().OfType<IMethodSymbol>())
                {
                    if (method.Name.StartsWith("Invoke_", StringComparison.Ordinal) ||
                        type.TypeKind == TypeKind.Struct && method.Name == "ToNative")
                    {
                        PreserveMethod(method.Name, typeName);
                    }
                }
            }

            source.AppendLine($"    private static void AddNamespace{i}(Dictionary<string, Type> types)");
            source.AppendLine("    {");
            source.Append(entries);
            source.AppendLine("    }");

            void AppendEntry(string name, string typeName) =>
                entries.AppendLine($"        types.Add({SymbolDisplay.FormatLiteral(name, true)}, typeof({typeName}));");
        }

        source.AppendLine("}");
        context.AddSource("UnrealSharpTypeMap.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));

        void PreserveConstructors(string typeName) =>
            source.AppendLine($"    [DynamicDependency(UnrealTypeRegistry.Constructors, typeof({typeName}))]");

        void PreserveMethod(string name, string typeName) =>
            source.AppendLine($"    [DynamicDependency({SymbolDisplay.FormatLiteral(name, true)}, typeof({typeName}))]");
    }

    private static string GetMetadataName(INamedTypeSymbol type)
    {
        if (type.ContainingType != null)
        {
            return GetMetadataName(type.ContainingType) + "+" + type.MetadataName;
        }

        return type.ContainingNamespace.IsGlobalNamespace
            ? type.MetadataName
            : type.ContainingNamespace.ToDisplayString() + "." + type.MetadataName;
    }
}
